apiVersion: v1
kind: Service
metadata:
  name: hivemq
  namespace: senior-care-hivemq
spec:
  type: ClusterIP
  selector:
    app: hivemq
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websocket
      port: 8000
      targetPort: 8000
