apiVersion: v1
kind: Service
metadata:
  name: senior-care-frontend
  namespace: senior-care-web
spec:
  type: NodePort
  selector:
    app: senior-care-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000