apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace:  senior-care-notification

spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - name: http
      port: 4002
      targetPort: 4002
    - name: grpc
      port: 50051
      targetPort: 50051